public class Player {
    public void playing() {
        string player1name = 'Hagi';
        string player2name = 'Alex';
        string player3name = 'Muslera';
        string player4name = 'Sergen';
        string player5name = 'Hami';

        system.debug('super Lig Player\'s name is ' + player1name);
        system.debug('super Lig Player\'s name is ' + player2name);
        system.debug('super Lig Player\'s name is ' + player3name);
        system.debug('super Lig Player\'s name is ' + player4name);
        system.debug('super Lig Player\'s name is ' +player5name);
    }
}

